apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
  type: NodePort
  ports:
  - port: 8070
    nodePort: 32333
    targetPort: 80
    protocol: TCP
    name: http
