apiVersion: apps/v1
kind: Deployment
metadata:
  name: jangoblog
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      run: jangoblog
  template:
    metadata:
      labels:
        run: jangoblog
    spec:
      containers:
      - name: jangoblog
        #image: bulletinboard:1.0
        image: ohyoungjooung/jango-blog:1.3
---
apiVersion: v1
kind: Service
metadata:
  name: jangoblog
  namespace: default
  labels:
    run: jangoblog
spec:
  type: NodePort
  selector:
    run: jangoblog
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
    nodePort: 30001
