---
- hosts: all
  sudo: yes
  tasks:
  - name: Ensure nfs-server installed
    yum: name=nfs-utils state=present

  - name: Ensure rpcbind running
    systemd:
     state: started
     name: "{{ item }}"
     enabled: yes
    with_items: 
     - rpcbind
     - nfs-server
     - nfs-lock
     - nfs-idmap


  - file:
      path: /nfsroot
      state: directory
      owner: nfsnobody
      group: nfsnobody
      mode: 0755

  - name: Creating /etc/exports
    shell: echo "/nfsroot 10.1.0.0/24(rw,sync,no_root_squash,no_all_squash)" > /etc/exports

  #- lineinfile: 
  #    path: /etc/exports
  #    line:  "/nfsroot 10.1.0.0/24(rw,sync,no_root_squash,no_all_squash)"

  - name: Restarting nfs-server 
    systemd:
     daemon_reload: yes
     name: nfs-server
     state: restarted
