apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  ports:
    - port: 9200
  selector:
    app: elasticsearch
  type: NodePort
  ports:
  - port: 9200
    targetPort: 9200
    nodePort: 32335
    protocol: TCP
    name: http
