kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage-claim-for-esearch
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
