apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-master
spec:
  selector:
    matchLabels:
      app: mariadb-master
  serviceName: mariadb-master
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb-master
    spec:
      containers:
      - name: mariadb-master
        image: ohyoungjooung2/mariadb:10.1.14-master
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
               name: mariadb-pass
               key: password
        - name: MYSQL_REPLICATION_USER
          valueFrom:
            secretKeyRef:
               name: rep-user
               key: rep-user

        - name: MYSQL_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
               name: rep-password
               key: rep-password
        ports:
        - name: mariadb-master
          containerPort: 3306
        volumeMounts:
        - name: mariadb-master-st
          mountPath: /var/lib/mysql
          subPath: mariadb
        - name: mariadb-master-cnf
          mountPath: /etc/mysql/conf.d

        resources:
          requests:
            cpu: 500m
            memory: 1Gi
    
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            # Check we can execute queries over TCP (skip-networking is off).
            command: ["mysql", "-h", "localhost","-pStrongPass$^^$","-e", "SELECT 1"]
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1

      volumes:
      - name: mariadb-master-cnf
        configMap:
          name: mariadb-master.cf

        
       
  volumeClaimTemplates:
  - metadata:
      name: mariadb-master-st
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "mariadb-master-sc"
      resources:
        requests:
          storage: 1Gi
