apiVersion: v1
kind: Service
metadata:
  name: mariadb-master
  labels:
    app: mariadb-master
spec:
  ports:
  - name: mariadb-master
    port: 3306
  clusterIP: None
  selector:
    app: mariadb-master
