apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  ports:
    - port: 8080
  selector:
    app: jenkins
  type: NodePort
  ports:
  - port: 8071
    nodePort: 32337
    targetPort: 8080
    protocol: TCP
    name: http
