apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-slave
spec:
  selector:
    matchLabels:
      app: mariadb-slave
  serviceName: mariadb-slave
  replicas: 2
  template:
    metadata:
      labels:
        app: mariadb-slave
    spec:
      initContainers:
      - name: init-mariadb-slave
        image: ohyoungjooung2/mariadb:10.1.14-slave2
        command:
        - bash
        - "-c"
        -  |
           set -ex
           [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
           ordinal=${BASH_REMATCH[1]}
           id=$(( $ordinal + 2 ))
           echo [mysqld] > /mnt/conf.d/server-id.cnf
           echo server-id=$id >> /mnt/conf.d/server-id.cnf
           echo log-bin >> /mnt/conf.d/server-id.cnf
           echo log-basename=slave$id >> /mnt/conf.d/server-id.cnf
           echo character_set_server=utf8 >> /mnt/conf.d/server-id.cnf
           echo collation_server=utf8_general_ci >> /mnt/conf.d/server-id.cnf

        volumeMounts:
        - name: conf
          mountPath: /mnt/conf.d
         
  
      containers:
      - name: mariadb
        image: ohyoungjooung2/mariadb:10.1.14-slave2
        lifecycle:
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "no"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
               name: mariadb-pass
               key: password
        - name: MYSQL_MASTER_SERVICE_HOST
          value: mariadb-master
          
        - name: MYSQL_REPLICATION_USER
          valueFrom:
            secretKeyRef:
               name: rep-user
               key: rep-user

        - name: MYSQL_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
               name: rep-password
               key: rep-password



        ports:
        - name: mariadb-slave
          containerPort: 3306
        volumeMounts:
        - name: mariadb-slave
          mountPath: /var/lib/mysql
          subPath: mariadb-sv
        - name: conf       
          mountPath: /etc/mysql/conf.d
 

        resources:
          requests:
            cpu: 500m
            memory: 1Gi

        livenessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5


      volumes:
      - name: conf
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      #name: data
      name: mariadb-slave
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "mariadb-slave-sc"
      resources:
        requests:
          storage: 1Gi
